import type { Metadata } from 'next';
import './globals.css';
import { Poppins } from 'next/font/google';
import HeroSection from '@/components/templates/HeroSection';
import { data } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default async function RootLayout({
  children,
  slider,
}: Readonly<{
  children: React.ReactNode;
  slider: React.ReactNode;
}>) {
  const profiles = await data('/api/profiles');

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <main className="overflow-x-hidden">
          <HeroSection profiles={profiles}>{slider}</HeroSection>
          {children}
        </main>
      </body>
    </html>
  );
}
